//   __
//  / _|
// | |     __     __    _ __    __   _ __
// | |    /  \   /  \  | /  \  / _| | /  \
// | |   | /\ | | /\ | |  /\ | \ \  |  /\ |
// | |_  | \/ | | \/ | | | | |  \ \ |  \/ |
//  \__|  \__/   \__/  |_| |_| |__/ |  __/  v.1
//                                  | |
//                                  |_|
//
// Criado por Matheus Cristian Santos Portela
// Facebook - www.facebook.com/mathuesJS
// em 23/08/2014(DD/MM/AAAA) às 19:27
(function(w){w.Coonsp=function(c){this.canvas=c;this.ctx=X;this.l=0;var c=this.canvas,X=this.canvas.getContext("2d"),u=new Date(),f=30,e={},C=true,b=false,a=false,F={},E=this,wi="width",he="height";this.start=function(){u=new Date();function s(){X.clearRect(0,0,c[wi],c[he]);if(b){F[b](E);}for(var i in e){if(e[i].type=="block"){var x=(e[i].x)?e[i].x:0;var y=(e[i].y)?e[i].y:0;var w=(e[i].w)?e[i].w:0;var h=(e[i].h)?e[i].h:0;if(e[i].ponto){var l=e[i].ponto.split("-");if(l[0]=="top"){y=y;}else if(l[0]=="bottom"){y=y+h;}else if(l[0]=="center"){y=y+(h/2);}if(l[1]=="left"){x=x;}else if(l[1]=="right"){x=x+w;}else if(l[1]=="center"){x=x+(w/2);}}X.save();X.translate(e[i].x,e[i].y);if(e[i].rotate){X.rotate(e[i].rotate*Math.PI/180);}X.fillRect(e[i].x-x,e[i].y-y,w,h);X.restore();}else if(e[i].type=="text"){var x=(e[i].x)?e[i].x:0;var y=(e[i].y)?e[i].y:0;var h=(e[i].size)?e[i].size:10;var w=X.measureText(e[i].content)[wi];var h=h*1.5;if(e[i].ponto){var l=e[i].ponto.split("-");if(l[0]=="top"){y=y;}else if(l[0]=="bottom"){y=y+h;}else if(l[0]=="center"){y=y+(h/2);}if(l[1]=="left"){x=x;}else if(l[1]=="right"){x=x+w;}else if(l[1]=="center"){x=x+(w/2);}}X.save();X.translate(e[i].x,e[i].y);if(e[i].rotate){X.rotate(e[i].rotate*Math.PI/180);}X.font=h+"px Arial";if(e[i].baseline){X.textBaseline=e[i].baseline;}if(e[i].align){X.textAlign=e[i].align;}X.fillText(e[i].content,e[i].x-x,e[i].y-y);X.restore();}else if(e[i].type=="img"){var x=(e[i].x)?e[i].x:0;var y=(e[i].y)?e[i].y:0;var w=(e[i].w)?e[i].w:0;var h=(e[i].h)?e[i].h:0;if(e[i].ponto){var l=e[i].ponto.split("-");if(l[0]=="top"){y=y;}else if(l[0]=="bottom"){y=y+h;}else if(l[0]=="center"){y=y+(h/2);}if(l[1]=="left"){x=x;}else if(l[1]=="right"){x=x+w;}else if(l[1]=="center"){x=x+(w/2);}}X.save();X.translate(e[i].x,e[i].y);if(e[i].rotate){X.rotate(e[i].rotate*Math.PI/180);}var I=new Image();I.src=e[i].src;X.drawImage(I,e[i].x-x,e[i].y-y,w,h);X.restore();}}if(a){F[a](E);}E.l++;if(C){setTimeout(s,1000/(f*((new Date()-u)/(1000/f))));}u=new Date();}setTimeout(s,1000/f);s();};this.stop=function(){C=false;};this.add=function(o){e[o.name]={};var name=String(o.name);delete o.name;e[name]=o;};this.exc=function(o){delete e[o.name];};this.edi=function(o,i){if(!i){var n=String(o.name);delete o.name;for(var i in o){e[n][i]=o[i];}}else{var n=String(o.name);delete o.name;for(var i in o){e[n][i]+=o[i];}}};this.fps=function(o){f=o;};this.before=function(o){b=o;};this.after=function(o){a=o;};this.frame=function(o,i){F[i]=o;};this.get=function(o){return e[o];}}})(window);
console.log("  __\n / _|\n| |     __     __    _ __    __   _ __\n| |    /  \\   /  \\  | /  \\  / _| | /  \\\n| |   | /\\ | | /\\ | |  /\\ | \\ \\  |  /\\ |\n| |_  | \\/ | | \\/ | | | | |  \\ \\ |  \\/ |\n \\__|  \\__/   \\__/  |_| |_| |__/ |  __/  v.1\n                                 | |\n                                 |_|\n\nCoonsp - Criado Por Matheus Cristian\nFacebook - www.facebook.com/mathuesJS");